spring:
  cloud:
    gateway:
      # 配置tote转发规则
      routes:
        - id: order-rote
          uri: lb://server-order
          predicates:
            - Path=/order/**
        - id: product-rote
          uri: lb://server-product
          predicates:
            - Path=/product/**
        - id: bing-rote
          uri: https://cn.bing.com
          predicates:
            - Path=/**